# Python stubs generated by omniidl from Example.idl
# DO NOT EDIT THIS FILE!

import omniORB, _omnipy
from omniORB import CORBA, PortableServer
_0_CORBA = CORBA


_omnipy.checkVersion(4,2, __file__, 1)

try:
    property
except NameError:
    def property(*args):
        return None


#
# Start of module "Example"
#
__name__ = "Example"
_0_Example = omniORB.openModule("Example", r"Example.idl")
_0_Example__POA = omniORB.openModule("Example__POA", r"Example.idl")


# interface Greetings
_0_Example._d_Greetings = (omniORB.tcInternal.tv_objref, "IDL:Example/Greetings:1.0", "Greetings")
omniORB.typeMapping["IDL:Example/Greetings:1.0"] = _0_Example._d_Greetings
_0_Example.Greetings = omniORB.newEmptyClass()
class Greetings :
    _NP_RepositoryId = _0_Example._d_Greetings[1]

    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")

    _nil = CORBA.Object._nil


_0_Example.Greetings = Greetings
_0_Example._tc_Greetings = omniORB.tcInternal.createTypeCode(_0_Example._d_Greetings)
omniORB.registerType(Greetings._NP_RepositoryId, _0_Example._d_Greetings, _0_Example._tc_Greetings)

# Greetings operations and attributes
Greetings._d_sayHello = ((), ((omniORB.tcInternal.tv_string,0), ), None)
Greetings._d_sendMessage = (((omniORB.tcInternal.tv_string,0), ), (), None)

# Greetings object reference
class _objref_Greetings (CORBA.Object):
    _NP_RepositoryId = Greetings._NP_RepositoryId

    def __init__(self, obj):
        CORBA.Object.__init__(self, obj)

    def sayHello(self, *args):
        return self._obj.invoke("sayHello", _0_Example.Greetings._d_sayHello, args)

    def sendMessage(self, *args):
        return self._obj.invoke("sendMessage", _0_Example.Greetings._d_sendMessage, args)

omniORB.registerObjref(Greetings._NP_RepositoryId, _objref_Greetings)
_0_Example._objref_Greetings = _objref_Greetings
del Greetings, _objref_Greetings

# Greetings skeleton
__name__ = "Example__POA"
class Greetings (PortableServer.Servant):
    _NP_RepositoryId = _0_Example.Greetings._NP_RepositoryId


    _omni_op_d = {"sayHello": _0_Example.Greetings._d_sayHello, "sendMessage": _0_Example.Greetings._d_sendMessage}

Greetings._omni_skeleton = Greetings
_0_Example__POA.Greetings = Greetings
omniORB.registerSkeleton(Greetings._NP_RepositoryId, Greetings)
del Greetings
__name__ = "Example"

#
# End of module "Example"
#
__name__ = "Example_idl"

_exported_modules = ( "Example", )

# The end.
